# Generated by Django 4.0.4 on 2022-04-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
