# Generated by Django 4.0.4 on 2022-04-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_artical_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
