# Generated by Django 4.0.4 on 2022-04-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_artical_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artical',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
